export const detailListMock = {
    "sessionid":"1647158432835zaHTDEmMaz",
    "status":true,
    "msg":"",
    "content":[
        {
            "_id":"622b373dd061851aeefeb9ef",
            "orderId":"0974221934cf47f4b614635241ee7138",
            "userId":"huangkai",
            "contactId":"42095fe3939940c291b80b6822d5d2ee",
            "passengerIdList":"cfde315481a146988ef66a0d6a44e25b",
            "shoppingId":"a239d51272214564b61d9c3750e2f119",
            "locale":"tc",
            "currency":"USD",
            "clientTime":"2022-03-11T19:49:03+08:00",
            "status":0,
            "changeId":"",
            "refundId":"",
            "__v":0,
            "shoppingInfo":{
                "_id":"622b371e9095bf1af7e02d41",
                "shoppingId":"a239d51272214564b61d9c3750e2f119",
                "currency":"HKD",
                "policyInfo":{
                    "baggageInfoList":[
                        {
                            "checkedNote":"Adult tickets: 30kg per person;",
                            "checkedFormatted":{
                                "sequenceNote":null,
                                "adultDetail":{
                                    "description":"Total dimensions (length + width + height) of each piece cannot exceed 158CM.",
                                    "weightAndPieceDesc":"30 kg per person",
                                    "weight":30,
                                    "piece":1
                                },
                                "childDetail":null,
                                "infantDetail":null
                            },
                            "handNote":"Adult: 1 piece(s), 7kg each per person;",
                            "handFormatted":{
                                "sequenceNote":null,
                                "adultDetail":{
                                    "description":"Total dimensions (length + width + height) of each piece cannot exceed 115CM.",
                                    "weightAndPieceDesc":"1 piece(s) per person, 7 kg each piece",
                                    "weight":7,
                                    "piece":1
                                },
                                "childDetail":null,
                                "infantDetail":null
                            }
                        }
                    ],
                    "penaltyInfoList":[
                        {
                            "cancelInfo":{
                                "note":"",
                                "formatted":{
                                    "adultList":[
                                        {
                                            "specialText":"-1",
                                            "timeText":"Before departure",
                                            "specialType":0
                                        },
                                        {
                                            "specialText":"-1",
                                            "timeText":"After departure",
                                            "specialType":0
                                        }
                                    ],
                                    "childList":[
                                        {
                                            "specialText":"-1",
                                            "timeText":"Before departure",
                                            "specialType":0
                                        },
                                        {
                                            "specialText":"-1",
                                            "timeText":"After departure",
                                            "specialType":0
                                        }
                                    ],
                                    "infantList":[
                                        {
                                            "specialText":"-1",
                                            "timeText":"Before departure",
                                            "specialType":0
                                        },
                                        {
                                            "specialText":"-1",
                                            "timeText":"After departure",
                                            "specialType":0
                                        }
                                    ],
                                    "concurrentDescription":""
                                },
                                "originText":{
                                    "adult":false,
                                    "child":false,
                                    "infant":false
                                },
                                "notAllowed":false,
                                "firstTimeChangeFreeNote":null
                            },
                            "changeInfo":{
                                "note":"",
                                "formatted":{
                                    "adultList":[
                                        {
                                            "specialText":"619",
                                            "timeText":"Before departure",
                                            "specialType":0
                                        },
                                        {
                                            "specialText":"619",
                                            "timeText":"After departure",
                                            "specialType":0
                                        }
                                    ],
                                    "childList":[
                                        {
                                            "specialText":"619",
                                            "timeText":"Before departure",
                                            "specialType":0
                                        },
                                        {
                                            "specialText":"619",
                                            "timeText":"After departure",
                                            "specialType":0
                                        }
                                    ],
                                    "infantList":[
                                        {
                                            "specialText":"619",
                                            "timeText":"Before departure",
                                            "specialType":0
                                        },
                                        {
                                            "specialText":"619",
                                            "timeText":"After departure",
                                            "specialType":0
                                        }
                                    ],
                                    "concurrentDescription":""
                                },
                                "originText":{
                                    "adult":false,
                                    "child":false,
                                    "infant":false
                                },
                                "notAllowed":false,
                                "firstTimeChangeFreeNote":null
                            },
                            "endorsementNote":"No endorsement.",
                            "specialNote":"",
                            "noShowCondition":"",
                            "flagInfoList":[

                            ],
                            "partialUseChangeInfo":null
                        }
                    ]
                },
                "sessionId":"1646999325723PkaxMXcHNT",
                "redisCode":"0413BRSBCN",
                "redisSchema":"1730-0205-9B-77-E&S-BRS-T0-LHR-TTN-1-BUS/0405*2340-0210-BA-486-E&V-LHR-T5-BCN-T1-1-32A|186.00-41.97-186.00-26.41-186.00-26.41|1/1/60-GBP$1/1/60-GBP$1/1/60-GBP",
                "__v":0,
                "flightGroupInfoList":[
                    {
                        "_id":"622b371e9095bf1af7e02d51",
                        "shoppingId":"a239d51272214564b61d9c3750e2f119",
                        "flightId":"d019d55a56384b7b9962c4bcdc3044ec",
                        "arriveMultCityName":"Barcelona",
                        "departMultCityName":"Bristol",
                        "arriveDateTimeFormat":"2022-04-14T01:50:00+08:00",
                        "departDateTimeFormat":"2022-04-13T17:30:00+08:00",
                        "duration":{
                            "h":"08",
                            "m":"20"
                        },
                        "__v":0,
                        "flightSegments":[
                            {
                                "_id":"622b371e9095bf1af7e02d5b",
                                "flightId":"d019d55a56384b7b9962c4bcdc3044ec",
                                "segmentId":"67498a296513486a9c64e7e61fe5ea67",
                                "aDateTime":"2022-04-13T19:35:00+08:00",
                                "dDateTime":"2022-04-13T17:30:00+08:00",
                                "dCityInfo":{
                                    "code":"BRS",
                                    "name":"Bristol"
                                },
                                "aCityInfo":{
                                    "code":"LHR",
                                    "name":"London"
                                },
                                "dPortInfo":{
                                    "code":"BRS",
                                    "name":"Bristol",
                                    "terminal":"T0"
                                },
                                "aPortInfo":{
                                    "code":"LHR",
                                    "name":" Heathrow",
                                    "terminal":"TTN"
                                },
                                "acrossDays":0,
                                "airlineInfo":{
                                    "code":"9B",
                                    "name":"9B",
                                    "isLCC":false
                                },
                                "craftInfo":{
                                    "name":"Bus",
                                    "minSeats":null,
                                    "maxSeats":null,
                                    "widthLevel":"",
                                    "craftType":"n/a"
                                },
                                "cabinClass":"Economy",
                                "subClass":"S",
                                "durationInfo":{
                                    "hour":"02",
                                    "min":"05"
                                },
                                "transferDurationInfo":{
                                    "hour":"04",
                                    "min":"05"
                                },
                                "flightNo":"77",
                                "segmentNo":1,
                                "__v":0
                            },
                            {
                                "_id":"622b371e9095bf1af7e02d5c",
                                "flightId":"d019d55a56384b7b9962c4bcdc3044ec",
                                "segmentId":"7ea7c56ee602499e9de33532bcb7a445",
                                "aDateTime":"2022-04-14T01:50:00+08:00",
                                "dDateTime":"2022-04-13T23:40:00+08:00",
                                "dCityInfo":{
                                    "code":"LHR",
                                    "name":"London"
                                },
                                "aCityInfo":{
                                    "code":"BCN",
                                    "name":"Barcelona"
                                },
                                "dPortInfo":{
                                    "code":"LHR",
                                    "name":" Heathrow",
                                    "terminal":"T5"
                                },
                                "aPortInfo":{
                                    "code":"BCN",
                                    "name":"Barcelona",
                                    "terminal":"T1"
                                },
                                "acrossDays":1,
                                "airlineInfo":{
                                    "code":"BA",
                                    "name":"BA",
                                    "isLCC":false
                                },
                                "craftInfo":{
                                    "name":"Airbus A320-200 Ceo (Sharklets)",
                                    "minSeats":null,
                                    "maxSeats":null,
                                    "widthLevel":"",
                                    "craftType":"A320"
                                },
                                "cabinClass":"Economy",
                                "subClass":"V",
                                "durationInfo":{
                                    "hour":"02",
                                    "min":"10"
                                },
                                "transferDurationInfo":"null",
                                "flightNo":"486",
                                "segmentNo":2,
                                "__v":0
                            }
                        ]
                    }
                ],
                "policyDetailInfo":{
                    "_id":"622b371e9095bf1af7e02d4b",
                    "shoppingId":"a239d51272214564b61d9c3750e2f119",
                    "priceId":"5e71e438c3ec4d6580d2554915685e3e",
                    "adultPrice":{
                        "salePrice":"1599",
                        "tax":"361"
                    },
                    "childPrice":{
                        "salePrice":"1599",
                        "tax":"227"
                    },
                    "infantPrice":{
                        "salePrice":"1599",
                        "tax":"227"
                    },
                    "avgPrice":1960,
                    "totalPrice":1960,
                    "ticketDeadlineType":1,
                    "__v":0
                }
            }
        }
    ]
};