export const flightGroupInfoList = [
    {
        arriveMultCityName: 'Bangkok',
        departDateTimeFormat: 'June 24, 2021',
        departMultCityName: 'Madrid',
        flightTripTitle: 'Departure flight',
        duration: '16h 5m',
        dDateFormat: 'Thu, Jun 24',
        flightSegments: [
            {
                segmentNo: 1,
                aDateTime: '2021/06/24 23:30:00',
                dCityInfo: {
                    code: 'MAD',
                    name: 'Madrid',
                    __typename: 'CitySimpleInfoPayload',
                },
                aCityInfo: {
                    code: 'IST',
                    name: 'Istanbul',
                    __typename: 'CitySimpleInfoPayload',
                },
                dMainCityInfo: null,
                aMainCityInfo: null,
                dMainCityDistance: null,
                aMainCityDistance: null,
                dPortInfo: {
                    code: 'MAD',
                    name: 'Madrid Barajas Airport',
                    terminal: '1',
                    __typename: 'AirportSimpleInfoPayload',
                },
                aPortInfo: {
                    code: 'IST',
                    name: 'Istanbul new airport',
                    terminal: null,
                    __typename: 'AirportSimpleInfoPayload',
                },
                arrivalDays: 0,
                airlineInfo: {
                    code: 'TK',
                    name: 'Turkish Airlines',
                    isLCC: false,
                    alliance: 'SA',
                    __typename: 'AirlineInfoPayload',
                    lowPrice: null,
                },
                craftInfo: {
                    name: 'Airbus A330-200',
                    minSeats: null,
                    maxSeats: 412,
                    widthLevel: 'Twin-aisle',
                    craftType: '332',
                    __typename: 'CraftInfoPayload',
                },
                cabinClass: 'Economy',
                crossingSignInfo: null,
                dDateTime: '2021/06/24 18:20:00',
                shareAirline: null,
                shareFlightNo: '',
                durationInfo: {
                    hour: 4,
                    min: 10,
                    __typename: 'DurationInfoPayload',
                },
                transferDurationInfo: null,
                stopInfoList: null,
                luggageDirectInfo: {
                    directStatus: 1,
                    directDesc: 'For flight transfers in Istanbul, baggage can be checked through.',
                    directTitle: '[Baggage Transfers]',
                    __typename: 'LuggageDirectInfoPayload',
                },
                flightNo: 'TK1860',
                flightFlag: 16,
                sequenceNo: 1,
                atbFlight: false,
                __typename: 'FlightInfoPayload',
                subClass: 'L',
            },
            {
                segmentNo: 1,
                aDateTime: '2021/06/25 15:25:00',
                dCityInfo: {
                    code: 'IST',
                    name: 'Istanbul',
                    __typename: 'CitySimpleInfoPayload',
                },
                aCityInfo: {
                    code: 'BKK',
                    name: 'Bangkok',
                    __typename: 'CitySimpleInfoPayload',
                },
                dMainCityInfo: null,
                aMainCityInfo: null,
                dMainCityDistance: null,
                aMainCityDistance: null,
                dPortInfo: {
                    code: 'IST',
                    name: 'Istanbul new airport',
                    terminal: null,
                    __typename: 'AirportSimpleInfoPayload',
                },
                aPortInfo: {
                    code: 'BKK',
                    name: 'Suvarnabhumi Airport',
                    terminal: null,
                    __typename: 'AirportSimpleInfoPayload',
                },
                arrivalDays: 0,
                airlineInfo: {
                    code: 'TK',
                    name: 'Turkish Airlines',
                    isLCC: false,
                    alliance: 'SA',
                    __typename: 'AirlineInfoPayload',
                    lowPrice: null,
                },
                craftInfo: {
                    name: 'Airbus A330-300',
                    minSeats: null,
                    maxSeats: 420,
                    widthLevel: 'Twin-aisle',
                    craftType: '333',
                    __typename: 'CraftInfoPayload',
                },
                cabinClass: 'Economy',
                crossingSignInfo: null,
                dDateTime: '2021/06/25 01:25:00',
                shareAirline: null,
                shareFlightNo: '',
                durationInfo: {
                    hour: 10,
                    min: 0,
                    __typename: 'DurationInfoPayload',
                },
                transferDurationInfo: {
                    hour: 1,
                    min: 55,
                    __typename: 'DurationInfoPayload',
                },
                stopInfoList: null,
                luggageDirectInfo: {
                    directStatus: 2,
                    directDesc:
                        'For flight transfers in Bangkok, baggage cannot be checked through. Please collect your baggage on arrival and check-in again.',
                    directTitle: '[Baggage Transfers]',
                    __typename: 'LuggageDirectInfoPayload',
                },
                flightNo: 'TK068',
                flightFlag: 16,
                sequenceNo: 2,
                atbFlight: false,
                __typename: 'FlightInfoPayload',
                subClass: 'L',
            },
        ],
        __typename: 'FlightGroupInfoPayload',
    },
];
