export const policyDetailInfo = {
    channelInfoList: [
        {
            channelType: 'CSD-WS',
            engineType: 'Ctrip',
            __typename: 'ChannelInfoPayload',
        },
    ],
    avgPrice: 529.2,
    ifMultPu: false,
    ticketDeadlineType: null,
    hasMemberPrice: false,
    hasAgencyModel: true,
    adultPrice: {
        salePrice: 275.3,
        tax: 253.9,
        discount: null,
        extraFee: null,
        bookingFee: 0,
        atolFee: 2.5,
        __typename: 'PriceInfoPayload',
    },
    childPrice: null,
    infantPrice: null,
    ifMultTicket: false,
    limitInfo: {
        adultLimitInfo: {
            minAge: 0,
            maxAge: 99,
            minPassengerCount: 1,
            maxPassengerCount: 9,
            __typename: 'PassengerLimitInfoPayload',
        },
        availableSeatCount: 4,
        childLimitInfo: {
            minAge: 0,
            maxAge: 99,
            minPassengerCount: 1,
            maxPassengerCount: 9,
            __typename: 'PassengerLimitInfoPayload',
        },
        isAddPassengerRequery: true,
        maxAge: 99,
        maxPassengerCount: 9,
        minAge: 0,
        minPassengerCount: 1,
        nationalityLimit: [],
        nationalityLimitType: 0,
        __typename: 'BookingLimitInfoPayload',
    },
    productNoticeInfo: {
        discountPrice: null,
        onlyAdult: null,
        multiPu: null,
        multiTicketNoticeList: [],
        transit:
            'A transit visa may be required for this journey, please ensure you have all necessary documents before booking.',
        huhehot: null,
        lcc: null,
        mationalityLimit: null,
        passengerLimit: null,
        ageLimit: null,
        diffAirport: null,
        minPassengerGreaterThanTwo: null,
        note: null,
        free24HourRefund: null,
        ticketDeadline: 'Once payment is confirmed, tickets will be issued within 24 hours',
        limitTimeFreeRefund: null,
        noteList: null,
        nearbyCityDistanceList: null,
        __typename: 'ProductNoticePayload',
    },
    noticeInfoList: [
        {
            type: 'RefundCoupon',
            title: '[COVID-19 Refund Alert]',
            content:
                "Due to the impact of COVID-19 worldwide, refunds will be processed in accordance with the latest airline policies. Please note that at the airline's discretion, refunds may be made in the form of airline vouchers. The final decision regarding the refund method will be made by the airline.",
            contentList: null,
            showType: 0,
            __typename: 'ShoppingNoticeInfoPayload',
        },
        {
            type: 'NoticeInfoTransit',
            title: '[Travel Restrictions]',
            content:
                'A transit visa may be required for this journey, please ensure you have all necessary documents before booking.',
            contentList: null,
            showType: 0,
            __typename: 'ShoppingNoticeInfoPayload',
        },
        {
            type: 'NoticeInfoTicketDeadline',
            title: '[Ticket Issuing Time]',
            content: 'Once payment is confirmed, tickets will be issued within 24 hours',
            contentList: null,
            showType: 0,
            __typename: 'ShoppingNoticeInfoPayload',
        },
    ],
    flightPolicyInfoList: [
        {
            airlineCode: 'TK',
            bookingChannel: 'GDS-WS',
            productTypes: null,
            productSourceNum: null,
            __typename: 'FlightPolicyInfoPayload',
        },
    ],
    ticketDeadlineInfo: {
        deadlineType: 1,
        promiseMinutes: 1440,
        __typename: 'TicketDeadlineInfoPayload',
    },
    hasBrandTier: true,
    createOrderSendCoins: true,
    creditCardPaymentInfoList: null,
    __typename: 'PolicyDetailInfoPayload',
};
